[BUGFIX] Avoid JS error if unminified versions are used
Setting plugin.tx_cookieman.settings.minify=0 causes JS error:
Uncaught TypeError: (intermediate value)(intermediate value)(intermediate value)(intermediate value)(...) is not a function